### ISSUE TITLE
폴더 구조, Router, GlobalStyles 셋팅

### ISSUE THREAD

**Issue by Yongveloper** [LM-channel-team-project/team23#4]
- [x] 폴더 구조 
+불필요한 파일 삭제
+폴더 이름 수정 Routes -> Pages
![1](https://user-images.githubusercontent.com/64254228/113713498-64c13d00-9722-11eb-84fb-a0bb898d3aac.PNG)

- [x]  Router

![2](https://user-images.githubusercontent.com/64254228/113662647-7a634200-96e3-11eb-864c-28f7dba5c109.PNG)

- [x] GlobalStyles 적용 

![3](https://user-images.githubusercontent.com/64254228/113795479-fadb7e80-9787-11eb-9312-186b809d1198.PNG)

App.tsx
![4](https://user-images.githubusercontent.com/64254228/113662684-8e0ea880-96e3-11eb-9658-ed0aa2f6e125.PNG)

**Comment by EastSun1616** [comment]
로컬에서 문제없이 잘 돌아갑니다. 다만, 폴더명을 Routes보단 Pages로 하는 것이 좋아보이는데 어떠신가요??

**Comment by Yongveloper** [comment]
아,  처음에 그렇게 했었는데 다시 Pages로 변경하겠습니다~

**Comment by Yongveloper** [comment]
> 로컬에서 문제없이 잘 돌아갑니다. 다만, 폴더명을 Routes보단 Pages로 하는 것이 좋아보이는데 어떠신가요??

아, 처음에 그렇게 했었는데 다시 Pages로 변경하겠습니다~
